# version: 2.1
# orbs:
#   node: circleci/node@4.1.0
# workflows:
#   node-tests:
#     jobs:
#       - node/test
jobs:
  test:
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests
orbs:
  node: circleci/node@4.1.0
version: 2.1
workflows:
          node_test:
    jobs:
      - node/test
