version: 2
general:
  branches:
    only:
     - master
     - test
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9.0

    steps:
      - checkout
      - run: npm install
      # - run: npm test